iterations: 5

busco:
  lineage: /g/data/xe2/references/busco/eudicots_odb10

origrefs:
  grandis: /g/data/xe2/references/eucalyptus/grandis/Egrandis_v2.fasta
  emel-scott-v1: /g/data/xe2/references/eucalyptus/emel_scott/Emelliodora_CSIROg1_SISH00000000.1.fasta
  ealb-scott-draft: /g/data/xe2/references/eucalyptus/scott-draft-refs/albens_off_all_1.fasta
  esid-scott-draft: /g/data/xe2/references/eucalyptus/scott-draft-refs/sideroxylon_off_all_1.fasta

mapping:
  aligners:
    - bwa
  refs:
    - grandisv2chl
    - emel-scott
  samplesets:
    - all_samples
  ngm:
    sensitivity: 0.5

varcall:
  minmapq:
    bwa: 20
    ngm: 4
  minbq: 15
  theta_prior: 0.1 # approx 10% of sites vary, it seems. Crazy!
  filters:
    default: >
      -i 'QUAL >= 10 &&
          ALT != "." &&
          INFO/DP >= 5 &&
          INFO/AN >= 3'
    strict: >
      -i 'QUAL >= 40 &&
          ALT != "." &&
          INFO/DP >= 20 &&
          ((INFO/AN / N_SAMPLES)*2) > 0.20 &&
          MAF >= 0.01'
    # Above is presence rate, >20%

samples:
  - CCA0003
  - CCA0016
  - CCA0037
  - CCA0038
  - CCA0124
  - CCA0137
  - CCA0164
  - CCA0175
  - CCA0218
  - CCA0248
  - CCA0266
  - CCA0278
  - CCA0375
  - CCA0390
  - CCA0405
  - CCA0431
  - CCA0455
  - CCA0465
  - CCA0466
  - CCA0525
  - CCA0572
  - CCA0575
  - CCA0615
  - CCA0650
  - CCA0671
  - CCA0672
  - CCA0677
  - CCA0681
  - CCA0684
  - CCA0687
  - CCA0691
  - CCA0695
  - CCA0700
  - CCA0704
  - CCA0705
  - CCA0706
  - CCA0708
  - CCA0724
  - CCA0728
  - CCA0733
  - CCA0736
  - CCA0743
  - CCA0744
  - CCA0751
  - CCA0755
  - CCA0758
  - CCA0761
  - CCA0768
  - CCA0773
  - CCA0790
  - CCA0800
  - CCA0807
  - CCA0808
  - CCA0813
  - CCA0819
  - CCA0831
  - CCA0837
  - CCA0848
  - CCA0866
  - CCA0874
  - CCA0904
  - CCA0920
  - CCA0931
  - CCA0933
  - CCA0937
  - CCA0941
  - CCA0951
  - CCA0964
  - CCA0965
  - CCA0971
  - CCA1037
  - CCA1085
  - CCA1111
  - CCA1122
  - CCA1135
  - CCA1192
  - CCA1212
  - CCA1256
  - CCA1266
  - CCA1267
  - CCA1268
  - CCA1290
  - CCA1297
  - CCA1300
  - CCA1302
  - CCA1366
  - CCA1370
  - CCA1377
  - CCA1413
  - CCA1439
  - CCA1474
  - CCA1478
  - CCA1479
  - CCA1480
  - CCA1504
  - CCA1505
  - CCA1506
  - CCA1507
  - CCA1543
  - CCA1564
  - CCA1594
  - CCA1644
  - CCA1650
  - CCA1653
  - CCA1654
  - CCA1655
  - CCA1657
  - CCA1660
  - CCA1680
  - CCA2812
  - CCA2829
  - CCA2857
  - CCA2909
  - CCA2917
  - CCA3005
  - CCA3011
  - CCA3012
  - CCA3035
  - CCA3041
  - CCA3051
  - CCA3056
  - CCA3062
  - CCA3092
  - CCA3107
  - CCA3130
  - CCA3147
  - CCA3176
  - CCA3216
  - CCA3217
  - CCA3247
  - CCA3248
  - CCA3250
  - CCA3261
  - CCA3263
  - CCA3271
  - CCA3322
  - CCA3451
  - CCA3464
  - CCA3471
  - CCA3651
  - CCA3711
  - CCA3821
  - CCA3837
  - CCA3841
  - CCA3887
  - CCA3893
  - CCA3899
  - CCA3916
  - CCA3997
  - CCA4029
  - CCA4034
  - CCA4557
  - CCA4706
  - CCA4770
  - CCA4776
  - CCA4821
  - CCA4877
  - CCA4913
  - CCA4939
  - CCA4957
  - CCA4960
  - CCA5060
  - CCA5180
  - CCA5319
  - CCA5408
  - CCA5430
  - CCA5558
  - CCA5568
  - CCA5597
  - CCA5615
  - CCA5616
  - CCA5918
  - CCA5922
  - CCA5926
  - CCA5946
  - CCA5976
  - CCA6033
  - CCA6041
  - CCA6869
  - CCA6870
  - CCA6871
  - EmelCSIRO
